### ISSUE TITLE
Page break,admin page settings wont close after "save", status bar for generation, generatin won't repeat+

### ISSUE THREAD

**Issue by KeepSmilin** [mithereal/opencart-pdf-catalog#3]
I've installed the new version. Image in intro is back again. However admin settings page is not closing on "save". You have to save then hit cancel. It's something wrong with that. Break page options (before/after) should be included in settings (I had to edit script to get rid of the last page always an empty one). To include or not intro should be also a settings option. For a client is good to have it but as admin when one wants to generate catalog by categories and then assemble them the intro is not required. One has to delete it and add it back for normal operation. For large categories it is no indication that feature is working before data is gathered (needs progress bar). Worked on 500+ item category by increasing php.ini memory to 128M. Once a category generated, it refuses to do it again. Don't know why. These are suggestions and I appreciate your efforts. Also including or not parent category would be great.

**Comment by mithereal** [comment]
i dont have time to fix right now but for the error 
but as far as the basedir issue this has to do with how your host is configured
try changing this line in catalog/controller/product/pdf_catalog

##
this line "$pdf_logo = xxx"  causes the openbasedir issue as you cant backlink dirs due to restriction see that if it cannot be read it defaults to the dir located in your helpers directory, for some reaason you can read and for some reason this confuses the script, most likely the location of your image is incorrect for the script
replace the first ($pdf_logo = "../../../../image/".$this->config->get('config_logo');) with the second ($pdf_logo = "pdf_catalog_default_logo.png";)
###
$pdf_logo = "../../../../image/".$this->config->get('config_logo');
            if(file_exists($pdf_logo) == false)
            {
                $pdf_logo = "pdf_catalog_default_logo.png";
            }

**Comment by mithereal** [comment]
havent heard in 2 months closing if this is still an issue please reopen

**Comment by KeepSmilin** [comment]
The "save" part is ok as well as the image. As for the rest is up to your promise/engagement.
Did not have to use the above code.
